version: 2
jobs:
  build:
    docker:
      - image: maxboh/circleci-miniconda-gdal
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Install Python deps in a venv
          command: |
            pip install -r requirements-dev.txt
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
          command: |
            python manage.py migrate
          command: |
            python manage.py runserver 4444
          background: true
          command: |
            python repair/tests/webtest.py
      - run:
          name: run py.test
          command: |
            DJANGO_SETTINGS_MODULE=repair.settings4tests
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
      - run:
          name: codecov
          command: |
            DJANGO_SETTINGS_MODULE=repair.settings4tests
            coverage run manage.py test
            codecov