version: 2
jobs:
  build:
    docker:
      - image: maxboh/circleci-miniconda-gdal
      - image: image: selenium/standalone-chrome
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Python deps in a venv
          command: |
            pip install -r requirements-dev.txt
          command: |
            python manage.py migrate
            python repair/tests/webtest.py
      - run:
          name: run selenium tests prep
          command: |
            python manage.py migrate
      - run:
          name: run server
          command: python manage.py runserver 4444
          background: true
      - run:
          name: run selenium tests
          command: |
            curl --retry-delay 5 --retry 10  --retry-connrefused http://localhost:4444
            python manage.py repair/tests/webtest.py
      - run:
          name: run py.test
          command: |
            DJANGO_SETTINGS_MODULE=repair.settings4tests
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
      - run:
          name: codecov
          command: |
            DJANGO_SETTINGS_MODULE=repair.settings4tests
            coverage run manage.py test
            codecov