version: 2
jobs:
  build:
    docker:
      - image: maxboh/docker-circleci-node-miniconda-gdal
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Python deps in a venv
          command: |
            pip install -r requirements-dev.txt
      - run:
          name: Install Javascript packages
          command: |
            yarn install
      - run:
          name: Install Javascript packages
          command: |
            node_modules/.bin/webpack --config repair/webpack.dev.config.js
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Migrate Test Database
          command: |
            DJANGO_SETTINGS_MODULE=repair.settings4tests
            python manage.py migrate
      - run:
          name: start Testserver
          command: |
            python manage.py runserver 4444
          background: true
      - run:
          name: run py.test
          command: |
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
      - run:
          name: codecov
          command: |
            DJANGO_SETTINGS_MODULE=repair.settings4tests
            coverage run manage.py test
            codecov