version: 2
jobs:
  build:
    docker:
      - image: maxboh/circleci-miniconda-gdal
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Python deps in a venv
          command: |
            pip install -r requirements-dev.txt
      - run:
          name: run py.test
          command: |
            DJANGO_SETTINGS_MODULE=repair.settings4tests
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
      - run:
          name: codecov
          command: |
            DJANGO_SETTINGS_MODULE=repair.settings4tests
            coverage run manage.py test
            codecov