version: 2
machine:
  environment:
    DJANGO_SETTINGS_MODULE: repair.settings4tests
jobs:
  screentest:
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run:
          command: |
            python repair/screenshot.py
      - store_artifacts:
          path: /tmp/artifacts


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - screentest
